inherit_from: .rubocop_todo.yml

require:
  - "rubocop-rspec"

AllCops:
  Exclude:
    - "Gemfile"
    - "dtg.gemspec"
    - "Guardfile"

# Defer to StandardRB
Lint:
  Enabled: false
Layout:
  Enabled: false
Style:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: 'never'

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
  - "spec/**/*.rb"

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails:
  Enabled: true

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 8

RSpec/NestedGroups:
  Max: 5

# Do not change original behavior of date/time
Rails/TimeZone:
  Enabled: false
